tempo:
  storage:
    trace:
      backend: s3
      s3:
        endpoint: ${WASABI_ENDPOINT}
        insecure: false
        forcepathstyle: true
        access_key: ${S3_TEMPO_ACCESS}
        secret_key: ${S3_TEMPO_SECRET}
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

