# Multi-tenant Tempo configuration for distributed tracing
# Auth disabled for admin access - customers still isolated via labels
multitenancy_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9096

# Distributor configuration
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

# Ingester configuration
ingester:
  max_block_duration: 5m
  trace_idle_period: 10s
  max_block_bytes: 1_000_000

# Metrics generator (optional - creates metrics from traces)
metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://mimir:8080/api/v1/push
        send_exemplars: true

# Storage configuration - using local filesystem for now
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

# Query frontend configuration
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

# Compactor configuration
compactor:
  compaction:
    block_retention: 720h  # 30 days

# Overrides configuration (inline, no external file needed)

