apiVersion: 1

datasources:
  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      httpHeaderName1: 'X-Scope-OrgID'
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    secureJsonData:
      httpHeaderValue1: 'admin'

  # Mimir datasource for metrics
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:8080/prometheus
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      httpHeaderName1: 'X-Scope-OrgID'
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    secureJsonData:
      httpHeaderValue1: 'admin'

  # Tempo datasource for traces
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    version: 1
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      httpHeaderName1: 'X-Scope-OrgID'
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: mimir
      serviceMap:
        datasourceUid: mimir
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
    secureJsonData:
      httpHeaderValue1: 'admin'

