#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - jq
  - ca-certificates
  - git
  - htop
ssh_authorized_keys:
  - ${ssh_pub_key}
runcmd:
  # Install Docker
  - curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  - sh /tmp/get-docker.sh
  - systemctl enable docker
  - systemctl start docker
  # Create data directory for local cache (S3 used for persistent storage)
  - mkdir -p /opt/observability-data
  - chown -R root:root /opt/observability-data
  - chmod 755 /opt/observability-data
  # Set up Docker log rotation
  - |
    cat > /etc/docker/daemon.json <<EOF
    {
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "3"
      }
    }
    EOF
  - systemctl restart docker
  # Install Tailscale for VPN access to admin tools
  - curl -fsSL https://tailscale.com/install.sh | sh
  - systemctl enable tailscaled
  - systemctl start tailscaled
  - echo "Docker and Tailscale installed successfully"


