apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-issuer
spec:
  acme:
    server: https://step-ca.step-ca.svc.cluster.local/acme/acme/directory
    email: pki-admin@ok
    privateKeySecretRef:
      name: step-ca-account-key
    solvers:
      - http01:
          ingress:
            class: nginx

