apiVersion: v1
kind: Namespace
metadata:
  name: step-ca
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-config
  namespace: step-ca
type: Opaque
stringData:
  password: changeit
  # Provide a real ca.json and keys in production. For bootstrap, mount placeholder.
  ca.json: |
    {
      "address": ":9000",
      "dns": ["step-ca.step-ca.svc.cluster.local"],
      "db": {"type": "badgerv2", "dataSource": "/home/step/db"},
      "authority": {
        "type": "soft",
        "provisioners": [
          {"type": "ACME", "name": "acme"}
        ]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: step-ca
  namespace: step-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: step-ca
  template:
    metadata:
      labels:
        app: step-ca
    spec:
      containers:
        - name: step-ca
          image: smallstep/step-ca:0.26.1
          args: ["/usr/local/bin/step-ca", "/home/step/config/ca.json"]
          ports:
            - containerPort: 9000
          env:
            - name: STEPPATH
              value: /home/step
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: step-ca-password
                  key: password
          volumeMounts:
            - name: config
              mountPath: /home/step/config
              readOnly: true
            - name: certs
              mountPath: /home/step/certs
              readOnly: true
            - name: secrets
              mountPath: /home/step/secrets
              readOnly: true
            - name: db
              mountPath: /home/step/db
      volumes:
        - name: config
          secret:
            secretName: step-ca-config
        - name: certs
          secret:
            secretName: step-ca-certs
        - name: secrets
          secret:
            secretName: step-ca-secrets
        - name: db
          persistentVolumeClaim:
            claimName: step-ca-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: step-ca-data
  namespace: step-ca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: step-ca
  namespace: step-ca
spec:
  selector:
    app: step-ca
  ports:
    - name: http
      port: 9000
      targetPort: 9000

