apiVersion: v1
kind: Namespace
metadata:
  name: net-dns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-ok-corefile
  namespace: net-dns
data:
  Corefile: |
    ok:53 {
      errors
      log
      file /zones/ok.db
    }
    .:53 {
      forward . 8.8.8.8 1.1.1.1
      cache 30
      errors
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-ok-zone
  namespace: net-dns
data:
  ok.db: |
    $ORIGIN ok.
    $TTL 60
    @   IN SOA ns1.ok. hostmaster.ok. (
            2025102501 ; serial
            60         ; refresh
            60         ; retry
            120        ; expire
            60 )       ; minimum
        IN NS ns1.ok.
    ns1.ok. IN A 127.0.0.1
    ; This record will be updated by a script later
    grafana IN A 100.84.84.76
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns-ok
  namespace: net-dns
  labels:
    app: coredns-ok
spec:
  selector:
    matchLabels:
      app: coredns-ok
  template:
    metadata:
      labels:
        app: coredns-ok
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: coredns
          image: coredns/coredns:1.11.1
          args: ["-conf", "/etc/coredns/Corefile"]
          ports:
            - containerPort: 53
              hostPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              hostPort: 53
              name: dns-tcp
              protocol: TCP
          volumeMounts:
            - name: corefile
              mountPath: /etc/coredns
              readOnly: true
            - name: zone
              mountPath: /zones
              readOnly: true
      volumes:
        - name: corefile
          configMap:
            name: coredns-ok-corefile
        - name: zone
          configMap:
            name: coredns-ok-zone

